"use client";

import type { SessionData, SessionName, Answer, UploadedPhoto } from "./types";

const STORAGE_KEY_PREFIX = "ring-log";

function storageKey(name: SessionName) {
  return `${STORAGE_KEY_PREFIX}-${name}`;
}

export function loadSession(name: SessionName): SessionData {
  try {
    const raw = localStorage.getItem(storageKey(name));
    if (raw) return JSON.parse(raw) as SessionData;
  } catch {}
  return { name, answers: [] };
}

export function saveSession(data: SessionData) {
  try {
    localStorage.setItem(storageKey(data.name), JSON.stringify(data));
  } catch {}
}

export function upsertAnswer(
  data: SessionData,
  answer: Answer
): SessionData {
  const existing = data.answers.findIndex((a) => a.questionId === answer.questionId);
  const updated = [...data.answers];
  if (existing >= 0) {
    updated[existing] = answer;
  } else {
    updated.push(answer);
  }
  return { ...data, answers: updated };
}

export function getAnswer(data: SessionData, questionId: string): Answer | undefined {
  return data.answers.find((a) => a.questionId === questionId);
}

// Build the preferences JSON for export
export function buildPreferencesJson(data: SessionData): Record<string, unknown> {
  const out: Record<string, unknown> = {
    name: data.name,
    completedAt: data.completedAt ?? new Date().toISOString(),
    answers: {} as Record<string, unknown>,
  };

  for (const answer of data.answers) {
    const photos =
      answer.photos?.map((p) => ({
        filename: p.filename,
        section: p.section,
        caption: p.caption ?? "",
        timestamp: p.timestamp,
      })) ?? [];

    (out.answers as Record<string, unknown>)[answer.questionId] = {
      value: answer.value,
      photos,
    };
  }

  return out;
}

// Collect all photos across all answers
export function getAllPhotos(data: SessionData): UploadedPhoto[] {
  return data.answers.flatMap((a) => a.photos ?? []);
}

// Generate README content
export function buildReadme(name: SessionName): string {
  const displayName = name === "eril" ? "Eril" : "Mar";
  return `# ${displayName} — Ring Log Export

## Structure

\`\`\`
exports/${name}/
├── ${name}-preferences.json    ← All quiz answers
├── photo-manifest.json         ← Photo index with metadata
├── photos/
│   ├── memory/                 ← Memories & meaningful moments
│   ├── stones/                 ← Stone & material references
│   ├── style-refs/             ← Jewellery & style references
│   └── inspiration/            ← General inspiration photos
└── README.md                   ← This file
\`\`\`

## Using photo-manifest.json in Figma

Each entry in \`photo-manifest.json\` contains:
- \`filename\` — the renamed file (e.g. \`${name}-memory-01.jpg\`)
- \`section\` — which folder it lives in (\`memory\`, \`stones\`, \`style-refs\`, \`inspiration\`)
- \`caption\` — any note the respondent added
- \`timestamp\` — when it was uploaded

Import photos into a Figma mood-board by section.
The \`section\` field maps directly to the folder structure above.

Generated by The Ring Log — Sang Jiwa Productions, 2026.
`;
}
